#!/usr/bin/with-contenv sh

. /usr/local/bin/mbtiles-base

# Compute the digest of available mbtiles files on container startup, unless a
# digest is already available.
if test -f "$mbtiles_digest_file"; then
  log "Existing mbtiles digest found in $mbtiles_digest_file"
else
  /usr/local/bin/save-mbtiles-digest "$(compute-mbtiles-digest)"
fi
